import { c as create_ssr_component } from "../../chunks/ssr.js";
import "../../chunks/firebase.js";
import "firebase/firestore";
import "firebase/auth";
const css = {
  code: ".mainContainer.svelte-1vokjb9{min-height:100vh;background:linear-gradient(to right, #000428, #000046);color:#FFFFFF;position:relative;display:flex;flex-direction:column}",
  map: `{"version":3,"file":"+layout.svelte","sources":["+layout.svelte"],"sourcesContent":["<script>\\r\\n    import { onMount } from \\"svelte\\";\\r\\n    import { auth, db } from '../lib/firebase/firebase';\\r\\n    import { getDoc, doc, setDoc} from 'firebase/firestore';\\r\\n    import { authStore } from '../store/store';\\r\\n\\r\\n    const nonAuthRoutes = ['/'];\\r\\n    \\r\\n    onMount(() => {\\r\\n        console.log(\\"Mounting\\");\\r\\n        const unsubscribe = auth.onAuthStateChanged(async (user) => {\\r\\n            const currentPath = window.location.pathname;\\r\\n\\r\\n            if (!user && !nonAuthRoutes.includes(currentPath)) {\\r\\n                window.location.href = \\"/\\";\\r\\n                return;\\r\\n            }\\r\\n\\r\\n            if (user && currentPath === \\"/\\") {\\r\\n                window.location.href = \\"/dashboard\\";\\r\\n                return;\\r\\n            }\\r\\n            \\r\\n            if (!user) {\\r\\n                return\\r\\n            }\\r\\n\\r\\n            let dataToSetToStore;\\r\\n            const docRef = doc(db, \\"users\\", user.uid);\\r\\n            const docSnap = await getDoc(docRef);\\r\\n            if(!docSnap.exists()) {\\r\\n                const userRef = doc(db, \\"users\\", user.uid);\\r\\n                dataToSetToStore = {\\r\\n                    email: user.email,\\r\\n                    todos: []\\r\\n                };\\r\\n                await setDoc(userRef, dataToSetToStore, { merge: true });\\r\\n            } else {\\r\\n                const userData = docSnap.data();\\r\\n                dataToSetToStore = userData;\\r\\n            }\\r\\n\\r\\n            authStore.update((curr) => {\\r\\n                return {\\r\\n                    ...curr,\\r\\n                    user,\\r\\n                    data: dataToSetToStore,\\r\\n                    loading: false,\\r\\n                }\\r\\n            })\\r\\n        })\\r\\n    })\\r\\n<\/script>\\r\\n\\r\\n<div class=\\"mainContainer\\">\\r\\n    <slot/>\\r\\n</div>\\r\\n\\r\\n<style>\\r\\n    .mainContainer {\\r\\n        min-height: 100vh;\\r\\n        background: linear-gradient(to right, #000428, #000046);\\r\\n        color: #FFFFFF;\\r\\n        position: relative;\\r\\n        display: flex;\\r\\n        flex-direction: column;\\r\\n    }\\r\\n</style>\\r\\n"],"names":[],"mappings":"AA2DI,6BAAe,CACX,UAAU,CAAE,KAAK,CACjB,UAAU,CAAE,gBAAgB,EAAE,CAAC,KAAK,CAAC,CAAC,OAAO,CAAC,CAAC,OAAO,CAAC,CACvD,KAAK,CAAE,OAAO,CACd,QAAQ,CAAE,QAAQ,CAClB,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MACpB"}`
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="mainContainer svelte-1vokjb9">${slots.default ? slots.default({}) : ``} </div>`;
});
export {
  Layout as default
};
